### PR TITLE
Update paper-color-picker to Polymer 1.0

### PR DESCRIPTION
**Pull request by IchordeDionysos**
I've updated the element to work in Polymer 1.* #4 and did some minor improvements:
 - improve paper ripple design (commit bfa3b75054c044fda74548a160575788ce1177f3)
 - change cursor on color-circle to crosshair (commit 098134033c2bebe7e4e7c188cb7a4f728622295d)
 - add scale-up and 
   fade-out animation to paper-dialog (commit 6278d258ec73db3609e8fe1617e11af40f11e72d)
 - add iron-components-page and link it to the demo for better documentation on the element (commits 11bf1d5171a30a52c9d0103a51567d7da5ade38e 44f9efcb74e40d6ee8f69282cdcc21a606237d6c 0c677463eb36e3bcb1d8973ce9966e88b2967347)

TODO: I don't how you wanted to implement huebox, so I left it out

### CODE REVIEW

**Comment by David-Mulder** [comment]
First of all, amazing work! Going to go through the commits and comment on a couple of things first, but definitely going to pull it all once it all works.

Note: Regarding the LICENSE, wanna switch to a LGPL or MIT license? The current license is GPL which doesn't allow commercial use (well, it does, but only open source commercial use, where anybody can take the code and make a free version) which I use when I am the sole contributor where I offer the component for commercial use for any donation (be it just a dollar or more xD). When users make very small contributions I just get their agreement that this is fine, but when users make bigger contributions I feel this would be unfair and thus I propose releasing the updated component under a new freer open source license.

**Comment by David-Mulder** [comment]
So, first of all, what about the license issue I asked about? I am merging it now so that I can fix and polish it up a bit, but without your permission to change the license I will have to revert it back.

**Comment by IchordeDionysos** [comment]
I think it definitely okay that you change the licence, change it to one of the you talked about earlier (LGPL or MIT license)!!

**Comment by David-Mulder** [comment]
And changed the LICENSE and fixed a lot of things... like honestly, with all due respect, but like half the component wasn't working (lightness/brightness sliders didn't work at all (huebox I knew about, so that was fine), capitalization stuff in attribute names, etc.)... and a lot of stuff wasn't migrated ('computedIf' function lying around for example).

Either way, think most of it (if not everything) is working now. Looking now at how to update this to the new material design spec that came out since I originally released the component.

**Comment by IchordeDionysos** [comment]
Lightness/Brightness sliders don't change the red/green/blue values if you mean this, but they change the lightness/brightness of the color-circle (at least in my example in my project, where I implemented it)

I knew that the element wasn't 100% perfect (the thing with lightness slider), but I thought this would help you a lot and I would have worked a lot on the element and think of it how to compute the lightness that it changes the red/green/blue values and not only the color circle/square

**Comment by David-Mulder** [comment]
@IchordeDionysos Yeah, no, it was supposed to only change the color circle/square... but... I am confused how it could work for you, because... oh wait, I know, you're using the proper Shadow DOM aren't you? And the demo is using the shady DOM (or the other way round)... oh wow, that's the one thing I absolutely hate about making elements in the Polymer 1.0 age: You need to support two different DOM models.

Oh well, in the end it still took me less time to fix all the issues then it would've taken me to migrate it from scratch, so you definitely have my thanks for that! I was just... lets say surprised how much stuff didn't work properly in the demo (the anti aliased circle was another one I forgot mentioning). Either way, working on a really really cool update right as we speak, so you have something to look forward to :+1:

**Pull request merged**
